name: flutterclient
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  link_text: ^0.2.1
  flutter_linkify: ^6.0.0
  firebase_database: ^11.1.4
  firebase_core: ^3.6.0
  url_launcher: ^6.3.1
  mysql_client: ^0.0.27


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
